### PR TITLE
Notifications

### PR DESCRIPTION
**Pull request by synth-ruiner**
ask permission after entering; on receiving chat from other users, if permission is given and the window is not in focus, notify ("username: message")

### CODE REVIEW

**Comment by Ragzouken** [comment]
i made some changes, mostly to make it work in chrome (if you don't have renotify it won't show more recent notifications), also moved permission request to command. lemme know if it still works as expected for you

**Comment by synth-ruiner** [comment]
does /notify need to be listed in the help command?

**Comment by synth-ruiner** [comment]
gonna leave zone open and see if I get a notification

**Comment by synth-ruiner** [comment]
works. all good

**Pull request merged**
